//@prepros-append ./plugins/jquery-1.12.4.min.js
//@prepros-append ./plugins/dropdown.js
//@prepros-append ./plugins/tabs.js
//@prepros-append ./plugins/collapse.js
//@prepros-append ./plugins/transition.js
//@prepros-append ./plugins/selectric.js
//@prepros-append ./plugins/carousel.js
//@prepros-append ./plugins/upload.js
//@prepros-append ./plugins/popup.js
